### ISSUE TITLE
WSL terminal just flashes

### ISSUE THREAD

**Issue by wodim** [mintty/wsltty#297]
I installed wsltty to be used with WSL1 and Ubuntu 20.04 and if I open the "ubuntu 20.04 terminal" shortcut the window just flashes. On the other hand if I open the "wsl terminal" shortcut I get the same flash but the window says "there is no distribution with the supplied name" or something like that (I can't make it out). Any help?

**Comment by Biswa96** [comment]
* Windows OS full version number?
* Output of `wsl.exe --list --verbose`? If that command exists.

**Comment by wodim** [comment]
* 1809 17763.2213
*
```Invalid command line option: --list
Usage: wsl.exe [option] ...
Options:
    -d, --distribution <DistributionName>
        Launch the specified distribition.

    -e, --exec <CommandLine>
        Execute the specified Linux command. The remainder of the arguments are
        used as the command line to execute.

    -u, --user <UserName>
        Run as the specified user.

    --help
        Display this usage information.

    --
        Stop parsing arguments and pass the remainder to the Linux process.```

**Comment by Biswa96** [comment]
I am not sure about the cause of this issue. For older Windows versions, try to use wsltty version [older than 3.0.5][1]. I have to spin up a VM to test that.

[1]: https://github.com/mintty/wsltty/releases?after=3.0.5

**Comment by wodim** [comment]
Thanks, that works.

**Comment by Biswa96** [comment]
Hi, I have spent some time with that Windows build 17763.379. This issue seems to be duplicate of https://github.com/mintty/wsltty/issues/206 and https://github.com/mintty/wsltty/issues/198. 

Due to obscure nature of WSL2 (like whole Windows OS) I have to rely on undocumented COM interface in [wslbridge2][1] project. The Windows build 17763.379 is using older COM interface. So, using older than 3.0.5 wsltty release is _better solution_.

If someone want to hack [wslbridge2][1], it can be modified for that Windows LTSC version like below:

```diff --git a/src/LxssUserSession.hpp b/src/LxssUserSession.hpp
index 7fb6c25..f454cd3 100644
--- a/src/LxssUserSession.hpp
+++ b/src/LxssUserSession.hpp
@@ -136,7 +136,6 @@ struct _ILxssUserSessionVtbl
     /* ILxssUserSession methods */
     void *CreateInstance;
     void *RegisterDistribution;
-    void *RegisterDistributionPipe;
 
     HRESULT(STDMETHODCALLTYPE *GetDistributionId)(
         ILxssUserSession *This,
```

[1]: https://github.com/Biswa96/wslbridge2

**Comment by Biswa96** [comment]
WSL in that Windows version seems to be some kind of mixture of old and new things. It has some code dated back when WSL was called ADSS (Android Subsytem). Also it has some new code for the WSL2 VM mode feature.

**Comment by wodim** [comment]
Can I just wait for a release? Will it take long? Thanks

**Comment by Biswa96** [comment]
You can use 3.0.2.3, no issue there. I just fixed it from my side. Mischief managed! 🪄

**Comment by mintty** [comment]
About to release mintty 3.5.2, can we combine this with a wslbridge2 release?

**Comment by mintty** [comment]
I've added https://github.com/Biswa96/wslbridge2/commit/41575379b416703c49e2687e957440239a4cdfb7
as an additional patch for wsltty and released 3.5.3.

**Comment by mailinglists35** [comment]
still experiencing this on LTSC 2019 fully updated and latest wsltty release

**Comment by mailinglists35** [comment]
![image](https://user-images.githubusercontent.com/2054302/202877421-ccaacb1f-22d7-400b-acc5-04676c1ac6b0.png)

**Comment by mailinglists35** [comment]
looks like i686 version cannot launch 64 bit wsl.exe (it does though launch full path to `C:\Program Files\WindowsApps\CanonicalGroupLimited.Ubuntu18.04onWindows_1804.2019.522.0_x64__79rhkp1fndgsc\ubuntu1804.exe`)

**Comment by mailinglists35** [comment]
also there seem to be no uninstaller. I did the 64bt and works fine. 
did 64bit install just override all i686 files, or are some of i686 now just lying around useless?

**Comment by mintty** [comment]
wsl.exe is kind of hidden in WOW mode (32 bit apps under Windows 64 bit) but you are not supposed to run wsl.exe anyway in mintty as  wsltty works via wslbridge2 instead, so this is a different issue.

**Comment by mintty** [comment]
This should be fixed (again?...) with 3.6.4.
